### ISSUE TITLE
[BUG] NetBSD 11.0 RC4 and generally NetBSD 11.0 support

### ISSUE THREAD

**Issue by drixter** [lsof-org/lsof#362]
**Describe the bug**
Unable to complile on NetBSD 11.0 RC4

**To Reproduce**
Download
configure fails
```
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for x86_64--netbsd-gcc... (cached) gcc
checking whether the compiler supports GNU C... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to enable C11 features... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
configure: error: Unknown NetBSD release: 11.0_RC4
*** Error code 1

Stop.
make[1]: stopped making "all" in /srv/NetBSD/pkgsrc/wip/lsof
*** Error code 1
```

**Expected behavior**
Add compatibility to NetBSD 11 and sucessfully compile

**Program output**
N/A

**Environment (please complete the following information):**

 - Kernel: 11.0RC4
 - OS: NetBSD
 - lsof Version: lsof-4.99.6
 - Origin: tarball

**Additional context**
Please fix :-)

**Comment by 0-wiz-0** [comment]
The patches used by pkgsrc are here:
https://github.com/NetBSD/pkgsrc/tree/trunk/sysutils/lsof/patches
with an additional file here:
https://github.com/NetBSD/pkgsrc/tree/trunk/sysutils/lsof/files
which makes it build & work on NetBSD 11.99.6/x86_64.

**Comment by drixter** [comment]
Yes, but it will be good to incorporate them into main code.

**Comment by 0-wiz-0** [comment]
Thank you for that!
I've tried building on NetBSD 11.99.6, and I see some build problems. I'll attach the 'make -k' log.
Some are missing headers, one is a bug in dnode.c, you can find the commit fixing this [here](https://github.com/NetBSD/pkgsrc/commit/ec3b55c90749ddc914c7da726a0de357de710ef9)

**Comment by 0-wiz-0** [comment]
Ok, github didn't like me uploading the file, so here it is:
```
make  all-am
gcc -DHAVE_CONFIG_H -I. -I.  -I./lib/dialects/netbsd -Iautotools -DAUTOTOOLS -I./lib -I./include -I./src  -fvisibility=hidden -g -O2 -DNETBSDV=11000000 -D_KMEMUSER -D__NAMECACHE_PRIVATE -DHASNFSVATTRP -I/usr/src/sys -DLSOF_VSTR=\"11.99.6\" -DHAS_LOCKF_H -DHASPROCFS_PFSROOT -MT src/lsof-arg.o -MD -MP -MF src/.deps/lsof-arg.Tpo -c -o src/lsof-arg.o `test -f 'src/arg.c' || echo './'`src/arg.c
In file included from ./lib/dialects/netbsd/dlsof.h:401,
                 from ./lib/common.h:253,
                 from src/arg.c:31:
/usr/src/sys/sys/lockf.h:46:23: warning: 'struct vop_advlock_args' declared inside parameter list will not be visible outside of this definition or declaration
   46 | int lf_advlock(struct vop_advlock_args *, struct lockf **, off_t);
      |                       ^~~~~~~~~~~~~~~~
src/arg.c: In function 'enter_network_address':
src/arg.c:1362:17: error: implicit declaration of function 'inet_pton' [-Wimplicit-function-declaration]
 1362 |             i = inet_pton(AF_INET6, wa, (void *)&n.a);
      |                 ^~~~~~~~~
*** Error code 1 (continuing)
gcc -DHAVE_CONFIG_H -I. -I.  -I./lib/dialects/netbsd -Iautotools -DAUTOTOOLS -I./lib -I./include -I./src  -fvisibility=hidden -g -O2 -DNETBSDV=11000000 -D_KMEMUSER -D__NAMECACHE_PRIVATE -DHASNFSVATTRP -I/usr/src/sys -DLSOF_VSTR=\"11.99.6\" -DHAS_LOCKF_H -DHASPROCFS_PFSROOT -MT src/lsof-main.o -MD -MP -MF src/.deps/lsof-main.Tpo -c -o src/lsof-main.o `test -f 'src/main.c' || echo './'`src/main.c
In file included from ./lib/dialects/netbsd/dlsof.h:401,
                 from ./lib/common.h:253,
                 from src/main.c:33:
/usr/src/sys/sys/lockf.h:46:23: warning: 'struct vop_advlock_args' declared inside parameter list will not be visible outside of this definition or declaration
   46 | int lf_advlock(struct vop_advlock_args *, struct lockf **, off_t);
      |                       ^~~~~~~~~~~~~~~~
src/main.c: In function 'main':
src/main.c:178:18: error: implicit declaration of function 'open'; did you mean 'popen'? [-Wimplicit-function-declaration]
  178 |     while (((i = open("/dev/null", O_RDWR, 0)) >= 0) && (i < 2))
      |                  ^~~~
      |                  popen
*** Error code 1 (continuing)
gcc -DHAVE_CONFIG_H -I. -I.  -I./lib/dialects/netbsd -Iautotools -DAUTOTOOLS -I./lib -I./include -I./src  -fvisibility=hidden -g -O2 -DNETBSDV=11000000 -D_KMEMUSER -D__NAMECACHE_PRIVATE -DHASNFSVATTRP -I/usr/src/sys -DLSOF_VSTR=\"11.99.6\" -DHAS_LOCKF_H -DHASPROCFS_PFSROOT -MT src/lsof-print.o -MD -MP -MF src/.deps/lsof-print.Tpo -c -o src/lsof-print.o `test -f 'src/print.c' || echo './'`src/print.c
In file included from ./lib/dialects/netbsd/dlsof.h:401,
                 from ./lib/common.h:253,
                 from src/print.c:31:
/usr/src/sys/sys/lockf.h:46:23: warning: 'struct vop_advlock_args' declared inside parameter list will not be visible outside of this definition or declaration
   46 | int lf_advlock(struct vop_advlock_args *, struct lockf **, off_t);
      |                       ^~~~~~~~~~~~~~~~
src/print.c: In function 'gethostnm':
src/print.c:496:18: error: implicit declaration of function 'inet_ntop' [-Wimplicit-function-declaration]
  496 |             if (!inet_ntop(af, ia, hbuf + 1, sizeof(hbuf) - 3)) {
      |                  ^~~~~~~~~
*** Error code 1 (continuing)
gcc -DHAVE_CONFIG_H -I. -I.  -I./lib/dialects/netbsd -Iautotools -DAUTOTOOLS -I./lib -I./include -I./src  -fvisibility=hidden -g -O2 -DNETBSDV=11000000 -D_KMEMUSER -D__NAMECACHE_PRIVATE -DHASNFSVATTRP -I/usr/src/sys -DLSOF_VSTR=\"11.99.6\" -DHAS_LOCKF_H -DHASPROCFS_PFSROOT -MT lib/lsof-dvch.o -MD -MP -MF lib/.deps/lsof-dvch.Tpo -c -o lib/lsof-dvch.o `test -f 'lib/dvch.c' || echo './'`lib/dvch.c
In file included from ./lib/dialects/netbsd/dlsof.h:401,
                 from lib/common.h:253,
                 from lib/dvch.c:31:
/usr/src/sys/sys/lockf.h:46:23: warning: 'struct vop_advlock_args' declared inside parameter list will not be visible outside of this definition or declaration
   46 | int lf_advlock(struct vop_advlock_args *, struct lockf **, off_t);
      |                       ^~~~~~~~~~~~~~~~
lib/dvch.c: In function 'open_dcache':
lib/dvch.c:630:21: error: implicit declaration of function 'open'; did you mean 'popen'? [-Wimplicit-function-declaration]
  630 |         if ((DCfd = open(DCpath[DCpathX], O_RDONLY, 0)) < 0) {
      |                     ^~~~
      |                     popen
*** Error code 1 (continuing)
gcc -DHAVE_CONFIG_H -I. -I.  -I./lib/dialects/netbsd -Iautotools -DAUTOTOOLS -I./lib -I./include -I./src  -fvisibility=hidden -g -O2 -DNETBSDV=11000000 -D_KMEMUSER -D__NAMECACHE_PRIVATE -DHASNFSVATTRP -I/usr/src/sys -DLSOF_VSTR=\"11.99.6\" -DHAS_LOCKF_H -DHASPROCFS_PFSROOT -MT lib/dialects/netbsd/lsof-dnode.o -MD -MP -MF lib/dialects/netbsd/.deps/lsof-dnode.Tpo -c -o lib/dialects/netbsd/lsof-dnode.o `test -f 'lib/dialects/netbsd/dnode.c' || echo './'`lib/dialects/netbsd/dnode.c
In file included from ./lib/dialects/netbsd/dlsof.h:401,
                 from ./lib/common.h:253,
                 from lib/dialects/netbsd/dnode.c:36:
/usr/src/sys/sys/lockf.h:46:23: warning: 'struct vop_advlock_args' declared inside parameter list will not be visible outside of this definition or declaration
   46 | int lf_advlock(struct vop_advlock_args *, struct lockf **, off_t);
      |                       ^~~~~~~~~~~~~~~~
In file included from ./lib/dialects/netbsd/machine.h:43,
                 from ./lib/common.h:41:
lib/dialects/netbsd/dnode.c: In function 'getmemsz':
/usr/src/sys/sys/param.h:208:33: error: 'PAGE_SHIFT' undeclared (first use in this function); did you mean 'PGSHIFT'?
  208 | #define ctob(x)         ((x) << PAGE_SHIFT)
      |                                 ^~~~~~~~~~
lib/dialects/netbsd/dnode.c:83:33: note: in expansion of macro 'ctob'
   83 |             Lf->sz = (SZOFFTYPE)ctob(vm.vm_tsize + vm.vm_dsize + vm.vm_ssize);
      |                                 ^~~~
/usr/src/sys/sys/param.h:208:33: note: each undeclared identifier is reported only once for each function it appears in
  208 | #define ctob(x)         ((x) << PAGE_SHIFT)
      |                                 ^~~~~~~~~~
lib/dialects/netbsd/dnode.c:83:33: note: in expansion of macro 'ctob'
   83 |             Lf->sz = (SZOFFTYPE)ctob(vm.vm_tsize + vm.vm_dsize + vm.vm_ssize);
      |                                 ^~~~
*** Error code 1 (continuing)
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I.  -I./lib/dialects/netbsd -Iautotools -DAUTOTOOLS -I./lib -I./include  -fvisibility=hidden -g -O2 -DNETBSDV=11000000 -D_KMEMUSER -D__NAMECACHE_PRIVATE -DHASNFSVATTRP -I/usr/src/sys -DLSOF_VSTR=\"11.99.6\" -DHAS_LOCKF_H -DHASPROCFS_PFSROOT -MT lib/liblsof_la-dvch.lo -MD -MP -MF lib/.deps/liblsof_la-dvch.Tpo -c -o lib/liblsof_la-dvch.lo `test -f 'lib/dvch.c' || echo './'`lib/dvch.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I. -I./lib/dialects/netbsd -Iautotools -DAUTOTOOLS -I./lib -I./include -fvisibility=hidden -g -O2 -DNETBSDV=11000000 -D_KMEMUSER -D__NAMECACHE_PRIVATE -DHASNFSVATTRP -I/usr/src/sys -DLSOF_VSTR=\"11.99.6\" -DHAS_LOCKF_H -DHASPROCFS_PFSROOT -MT lib/liblsof_la-dvch.lo -MD -MP -MF lib/.deps/liblsof_la-dvch.Tpo -c lib/dvch.c  -fPIC -DPIC -o lib/.libs/liblsof_la-dvch.o
In file included from ./lib/dialects/netbsd/dlsof.h:401,
                 from lib/common.h:253,
                 from lib/dvch.c:31:
/usr/src/sys/sys/lockf.h:46:23: warning: 'struct vop_advlock_args' declared inside parameter list will not be visible outside of this definition or declaration
   46 | int lf_advlock(struct vop_advlock_args *, struct lockf **, off_t);
      |                       ^~~~~~~~~~~~~~~~
lib/dvch.c: In function 'open_dcache':
lib/dvch.c:630:21: error: implicit declaration of function 'open'; did you mean 'popen'? [-Wimplicit-function-declaration]
  630 |         if ((DCfd = open(DCpath[DCpathX], O_RDONLY, 0)) < 0) {
      |                     ^~~~
      |                     popen
*** Error code 1 (continuing)
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I.  -I./lib/dialects/netbsd -Iautotools -DAUTOTOOLS -I./lib -I./include  -fvisibility=hidden -g -O2 -DNETBSDV=11000000 -D_KMEMUSER -D__NAMECACHE_PRIVATE -DHASNFSVATTRP -I/usr/src/sys -DLSOF_VSTR=\"11.99.6\" -DHAS_LOCKF_H -DHASPROCFS_PFSROOT -MT lib/dialects/netbsd/liblsof_la-dnode.lo -MD -MP -MF lib/dialects/netbsd/.deps/liblsof_la-dnode.Tpo -c -o lib/dialects/netbsd/liblsof_la-dnode.lo `test -f 'lib/dialects/netbsd/dnode.c' || echo './'`lib/dialects/netbsd/dnode.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I. -I./lib/dialects/netbsd -Iautotools -DAUTOTOOLS -I./lib -I./include -fvisibility=hidden -g -O2 -DNETBSDV=11000000 -D_KMEMUSER -D__NAMECACHE_PRIVATE -DHASNFSVATTRP -I/usr/src/sys -DLSOF_VSTR=\"11.99.6\" -DHAS_LOCKF_H -DHASPROCFS_PFSROOT -MT lib/dialects/netbsd/liblsof_la-dnode.lo -MD -MP -MF lib/dialects/netbsd/.deps/liblsof_la-dnode.Tpo -c lib/dialects/netbsd/dnode.c  -fPIC -DPIC -o lib/dialects/netbsd/.libs/liblsof_la-dnode.o
In file included from ./lib/dialects/netbsd/dlsof.h:401,
                 from ./lib/common.h:253,
                 from lib/dialects/netbsd/dnode.c:36:
/usr/src/sys/sys/lockf.h:46:23: warning: 'struct vop_advlock_args' declared inside parameter list will not be visible outside of this definition or declaration
   46 | int lf_advlock(struct vop_advlock_args *, struct lockf **, off_t);
      |                       ^~~~~~~~~~~~~~~~
In file included from ./lib/dialects/netbsd/machine.h:43,
                 from ./lib/common.h:41:
lib/dialects/netbsd/dnode.c: In function 'getmemsz':
/usr/src/sys/sys/param.h:208:33: error: 'PAGE_SHIFT' undeclared (first use in this function); did you mean 'PGSHIFT'?
  208 | #define ctob(x)         ((x) << PAGE_SHIFT)
      |                                 ^~~~~~~~~~
lib/dialects/netbsd/dnode.c:83:33: note: in expansion of macro 'ctob'
   83 |             Lf->sz = (SZOFFTYPE)ctob(vm.vm_tsize + vm.vm_dsize + vm.vm_ssize);
      |                                 ^~~~
/usr/src/sys/sys/param.h:208:33: note: each undeclared identifier is reported only once for each function it appears in
  208 | #define ctob(x)         ((x) << PAGE_SHIFT)
      |                                 ^~~~~~~~~~
lib/dialects/netbsd/dnode.c:83:33: note: in expansion of macro 'ctob'
   83 |             Lf->sz = (SZOFFTYPE)ctob(vm.vm_tsize + vm.vm_dsize + vm.vm_ssize);
      |                                 ^~~~
*** Error code 1 (continuing)
`all-am' not remade because of errors.
```

**Comment by jiegec** [comment]
I have pushed a fix at fix-netbsd branch. For the missing declarations, it could be due to gcc upgraded to 16, and the `-Wno-implicit-function-declaration` compilation flag is gone. Please test.

**Comment by 0-wiz-0** [comment]
Thank you, that does finish compilation with only one warning (repeated quite often):
```
In file included from ./lib/dialects/netbsd/dlsof.h:401,
                 from ./lib/common.h:253,
                 from lib/dialects/netbsd/dproc.c:36:
/usr/src/sys/sys/lockf.h:46:23: warning: 'struct vop_advlock_args' declared inside parameter list will not be visible outside of this definition or declaration
   46 | int lf_advlock(struct vop_advlock_args *, struct lockf **, off_t);
      |                       ^~~~~~~~~~~~~~~~
```
But there is a problem at runtime, just plain 'lsof' does not print the NAME column correctly.
I fixed this problem [recently in pkgsrc](https://github.com/NetBSD/pkgsrc/commit/9bae78670aa1b67a625ed976796eba3fb36c90f8) please apply the diff.

**Comment by jiegec** [comment]
Thanks, fix applied to fix-netbsd branch.

**Comment by 0-wiz-0** [comment]
Thank you, builds and works (as far as I tested) on NetBSD 11.99.6/x86_64 now.
